theme = "dark_plus"

[editor]
# line-number = "relative"
# Show "tabs" for buffer at the top.
bufferline = "always"
# Some terminal required it for some theme to work.
true-color = true
# Save when switching betweens buffer.
auto-save = true
# Only one letter to trigger auto-completion (default 2).
completion-trigger-len = 1
# Increase timeout on LSP request as inlay hints can take quite some times (default 400).
idle-timeout = 800
# Instant auto-completion
completion-timeout = 5

[editor.statusline]
right = ["workspace-diagnostics", "selections", "register", "position-percentage", "spacer", "file-encoding"]

[editor.lsp]
display-inlay-hints = true
# Uncomment if you want more info about what the lsp is doing
# display-message = true

[editor.smart-tab]
supersede-menu = true

# Make it easier to know in which mode we are.
[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

# Make long lines fit the screen size.
# Useful when working with markdown.
[editor.soft-wrap]
enable = true
wrap-indicator = ""

[editor.file-picker]
# Show hidden files inside the picker.
hidden = false
# Uncomment if you want the file-picker to search even within git ignored files.
# git-ignore = false

# Show explicitly the indentation.
[editor.indent-guides]
render = true
character = "▏"

# Uncomment if you need to see whitespaces
# [editor.whitespace]
# render = "all"

[keys.insert]
C-k = "normal_mode"

[keys.select]
C-k = "normal_mode"

[keys.normal]
C-k = "normal_mode"
# Better vertical movement (from the Primeagen)
C-u = ["half_page_up", "align_view_center"]
C-d = ["half_page_down", "align_view_center"]

C-s = ":w"
C-space = "save_selection"
