# Colors (Google)
# https://github.com/alacritty/alacritty-theme/blob/master/themes/google.toml
[colors.bright]
black = "#969896"
blue = "#3971ed"
cyan = "#3971ed"
green = "#198844"
magenta = "#a36ac7"
red = "#cc342b"
white = "#ffffff"
yellow = "#fba922"

[colors.normal]
black = "#1d1f21"
blue = "#3971ed"
cyan = "#3971ed"
green = "#198844"
magenta = "#a36ac7"
red = "#cc342b"
white = "#c5c8c6"
yellow = "#fba922"

[colors.primary]
background = "#1d1f21"
foreground = "#c5c8c6"

# sudo apt install fonts-jetbrains-mono
[font.normal]
family = "JetBrains Mono"

[shell]
program = "/usr/bin/fish"
