[language-server.rust-analyzer]
config = { cargo = { features = "all" }, check = { command = "clippy" }, diagnostics = { disabled = ["inactive-code"]}}

[[language]]
name = "toml"
formatter = { command = "taplo", args = ["fmt", "-"]}
